/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import graphe.*;
import static graphe.Chargement.g;

/**
 *
 * @author rafik
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarOptions = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemOuvrir = new javax.swing.JMenuItem();
        jMenuItemModifier = new javax.swing.JMenuItem();
        jMenuAffichage = new javax.swing.JMenu();
        jMenuItemVoisinsDirects = new javax.swing.JMenuItem();
        jMenuItemLiensArete = new javax.swing.JMenuItem();
        jMenuFiltres = new javax.swing.JMenu();
        jMenuItemCriteres = new javax.swing.JMenuItem();
        jMenuItemFiabilité = new javax.swing.JMenuItem();
        jMenuItemCheminCourt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface d'aide à la décision");
        setPreferredSize(new java.awt.Dimension(700, 450));

        jMenuFichier.setText("Fichier");

        jMenuItemOuvrir.setText("Ouvrir");
        jMenuItemOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemOuvrir);

        jMenuItemModifier.setText("Modifier");
        jMenuFichier.add(jMenuItemModifier);

        jMenuBarOptions.add(jMenuFichier);

        jMenuAffichage.setText("Affichage");

        jMenuItemVoisinsDirects.setText("Voisins directs");
        jMenuAffichage.add(jMenuItemVoisinsDirects);

        jMenuItemLiensArete.setText("Liens arête");
        jMenuAffichage.add(jMenuItemLiensArete);

        jMenuBarOptions.add(jMenuAffichage);

        jMenuFiltres.setText("Filtres");

        jMenuItemCriteres.setText("Critères");
        jMenuFiltres.add(jMenuItemCriteres);

        jMenuItemFiabilité.setText("Fiabilité");
        jMenuFiltres.add(jMenuItemFiabilité);

        jMenuItemCheminCourt.setText("Chemin le plus court");
        jMenuFiltres.add(jMenuItemCheminCourt);

        jMenuBarOptions.add(jMenuFiltres);

        setJMenuBar(jMenuBarOptions);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirActionPerformed
        // TODO add your handling code here:
        Chargement.ouverture();
    }//GEN-LAST:event_jMenuItemOuvrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAffichage;
    private javax.swing.JMenuBar jMenuBarOptions;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenu jMenuFiltres;
    private javax.swing.JMenuItem jMenuItemCheminCourt;
    private javax.swing.JMenuItem jMenuItemCriteres;
    private javax.swing.JMenuItem jMenuItemFiabilité;
    private javax.swing.JMenuItem jMenuItemLiensArete;
    private javax.swing.JMenuItem jMenuItemModifier;
    private javax.swing.JMenuItem jMenuItemOuvrir;
    private javax.swing.JMenuItem jMenuItemVoisinsDirects;
    // End of variables declaration//GEN-END:variables
}
