/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import graphe.*;
import static graphe.Chargement.g;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rafik
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogListe = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaListe = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jDialogAretes = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaListe1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jDialogLiens = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jDialogLiensA = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDialogVoisinsD = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jDialogCheminCourt = new javax.swing.JDialog();
        jScrollPane14 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jScrollPane15 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jDialogFiabilite = new javax.swing.JDialog();
        jScrollPane17 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        jScrollPane18 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBarOptions = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemOuvrir = new javax.swing.JMenuItem();
        jMenuItemModifier = new javax.swing.JMenuItem();
        jDialog = new javax.swing.JMenu();
        jMenuItemListeSommets = new javax.swing.JMenuItem();
        jMenuItemListeAretes = new javax.swing.JMenuItem();
        jMenuFiltres = new javax.swing.JMenu();
        jMenuItemLiensSommet = new javax.swing.JMenuItem();
        jMenuItemLiensArete = new javax.swing.JMenuItem();
        jMenuItemVoisinsDirects = new javax.swing.JMenuItem();
        jMenuItemCheminCourt = new javax.swing.JMenuItem();
        jMenuItemFiabilité = new javax.swing.JMenuItem();
        jMenuItemCriteres = new javax.swing.JMenuItem();

        jDialogListe.setTitle("Liste des sommets");

        jTextAreaListe.setColumns(20);
        jTextAreaListe.setLineWrap(true);
        jTextAreaListe.setRows(5);
        jScrollPane6.setViewportView(jTextAreaListe);

        jLabel13.setText("Tous les sommets");

        javax.swing.GroupLayout jDialogListeLayout = new javax.swing.GroupLayout(jDialogListe.getContentPane());
        jDialogListe.getContentPane().setLayout(jDialogListeLayout);
        jDialogListeLayout.setHorizontalGroup(
            jDialogListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(jDialogListeLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogListeLayout.setVerticalGroup(
            jDialogListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jDialogAretes.setTitle("Liste des arêtes");

        jTextAreaListe1.setColumns(20);
        jTextAreaListe1.setLineWrap(true);
        jTextAreaListe1.setRows(5);
        jScrollPane7.setViewportView(jTextAreaListe1);

        jLabel7.setText("Tous les liens existants");

        jLabel8.setText("Total");

        jScrollPane9.setViewportView(jTextPane5);

        javax.swing.GroupLayout jDialogAretesLayout = new javax.swing.GroupLayout(jDialogAretes.getContentPane());
        jDialogAretes.getContentPane().setLayout(jDialogAretesLayout);
        jDialogAretesLayout.setHorizontalGroup(
            jDialogAretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAretesLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jDialogAretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogAretesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogAretesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jDialogAretesLayout.setVerticalGroup(
            jDialogAretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAretesLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jDialogAretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

<<<<<<< HEAD
=======
        jDialogLiens.setTitle("Liens d'un sommet donné");
        jDialogLiens.setPreferredSize(new java.awt.Dimension(500, 500));

>>>>>>> 4924503d8d3b4eef148e3d5377b4efc6808b9e4b
        jLabel5.setText("Sommet à traiter");

        jScrollPane5.setViewportView(jList1);

        jButton4.setText("OK");
        jButton4.setToolTipText("");

        jLabel6.setText("Liens du sommet");

        jScrollPane8.setViewportView(jList2);

        javax.swing.GroupLayout jDialogLiensLayout = new javax.swing.GroupLayout(jDialogLiens.getContentPane());
        jDialogLiens.getContentPane().setLayout(jDialogLiensLayout);
        jDialogLiensLayout.setHorizontalGroup(
            jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(51, 51, 51))
            .addGroup(jDialogLiensLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogLiensLayout.setVerticalGroup(
            jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton4)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jDialogLiensA.setTitle("Liens d'une arête donnée");

        jScrollPane10.setViewportView(jList3);

        jLabel9.setText("Arête à choisir");

        jScrollPane11.setViewportView(jList4);

        jLabel10.setText("Liens vers les sommets");

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogLiensALayout = new javax.swing.GroupLayout(jDialogLiensA.getContentPane());
        jDialogLiensA.getContentPane().setLayout(jDialogLiensALayout);
        jDialogLiensALayout.setHorizontalGroup(
            jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensALayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLiensALayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLiensALayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jDialogLiensALayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogLiensALayout.setVerticalGroup(
            jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensALayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jDialogLiensALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton5)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jDialogVoisinsD.setTitle("Liste des Sommets voisin d'un sommet donné");

        jLabel11.setText("Sommet(s) à choisir");

        jScrollPane12.setViewportView(jList5);

        jLabel12.setText("Sommets voisin");

        jScrollPane13.setViewportView(jList6);

        jButton6.setText("OK");

        javax.swing.GroupLayout jDialogVoisinsDLayout = new javax.swing.GroupLayout(jDialogVoisinsD.getContentPane());
        jDialogVoisinsD.getContentPane().setLayout(jDialogVoisinsDLayout);
        jDialogVoisinsDLayout.setHorizontalGroup(
            jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVoisinsDLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVoisinsDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(173, 173, 173))
            .addGroup(jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVoisinsDLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(253, 253, 253)))
        );
        jDialogVoisinsDLayout.setVerticalGroup(
            jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVoisinsDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jDialogVoisinsDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVoisinsDLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        jDialogCheminCourt.setTitle("Chemin le plus court entre deux sommets");
        jDialogCheminCourt.setPreferredSize(new java.awt.Dimension(600, 300));

        jScrollPane14.setViewportView(jList7);

        jScrollPane15.setViewportView(jList8);

        jLabel14.setText("1er sommet");

        jLabel15.setText("2ème sommet");

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane16.setViewportView(jTextArea1);

        jLabel16.setText("Chemin le plus court entre les deux sommets choisis");

        javax.swing.GroupLayout jDialogCheminCourtLayout = new javax.swing.GroupLayout(jDialogCheminCourt.getContentPane());
        jDialogCheminCourt.getContentPane().setLayout(jDialogCheminCourtLayout);
        jDialogCheminCourtLayout.setHorizontalGroup(
            jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheminCourtLayout.createSequentialGroup()
                .addGroup(jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheminCourtLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel14)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel15))
                    .addGroup(jDialogCheminCourtLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogCheminCourtLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheminCourtLayout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCheminCourtLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(38, 38, 38))))
        );
        jDialogCheminCourtLayout.setVerticalGroup(
            jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheminCourtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jDialogCheminCourtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogCheminCourtLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jDialogFiabilite.setTitle("Chemin le plus fiable entre deux sommets");
        jDialogFiabilite.setPreferredSize(new java.awt.Dimension(600, 300));

        jScrollPane17.setViewportView(jList9);

        jScrollPane18.setViewportView(jList10);

        jLabel17.setText("1er sommet");

        jLabel18.setText("2ème sommet");

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane19.setViewportView(jTextArea2);

        jLabel19.setText("Chemin le plus fiable entre les deux sommets choisis");

        javax.swing.GroupLayout jDialogFiabiliteLayout = new javax.swing.GroupLayout(jDialogFiabilite.getContentPane());
        jDialogFiabilite.getContentPane().setLayout(jDialogFiabiliteLayout);
        jDialogFiabiliteLayout.setHorizontalGroup(
            jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFiabiliteLayout.createSequentialGroup()
                .addGroup(jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogFiabiliteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel17)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel18))
                    .addGroup(jDialogFiabiliteLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogFiabiliteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogFiabiliteLayout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogFiabiliteLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap())))
        );
        jDialogFiabiliteLayout.setVerticalGroup(
            jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFiabiliteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jDialogFiabiliteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDialogFiabiliteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface d'aide à la décision");
        setPreferredSize(new java.awt.Dimension(700, 450));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);

        jButton2.setText("Supprimer");
        jButton2.setEnabled(false);

        jTextPane1.setEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Temps moyen");

        jTextPane2.setEnabled(false);
        jScrollPane2.setViewportView(jTextPane2);

        jLabel2.setText("Distance");

        jTextPane3.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane3);

        jLabel3.setText("Fiabilité");

        jTextPane4.setEnabled(false);
        jScrollPane4.setViewportView(jTextPane4);

        jLabel4.setText("Type de dispensaire");

        jButton3.setText("Modifier");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuFichier.setText("Fichier");

        jMenuItemOuvrir.setText("Ouvrir");
        jMenuItemOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemOuvrir);

        jMenuItemModifier.setText("Modifier");
        jMenuItemModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifierActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemModifier);

        jMenuBarOptions.add(jMenuFichier);

        jDialog.setText("Affichage");

        jMenuItemListeSommets.setText("Liste sommets");
        jMenuItemListeSommets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListeSommetsActionPerformed(evt);
            }
        });
        jDialog.add(jMenuItemListeSommets);

        jMenuItemListeAretes.setText("Liste arêtes");
        jMenuItemListeAretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListeAretesActionPerformed(evt);
            }
        });
        jDialog.add(jMenuItemListeAretes);

        jMenuBarOptions.add(jDialog);

        jMenuFiltres.setText("Filtres");

        jMenuItemLiensSommet.setText("Liens sommet");
        jMenuItemLiensSommet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLiensSommetActionPerformed(evt);
            }
        });
        jMenuFiltres.add(jMenuItemLiensSommet);

        jMenuItemLiensArete.setText("Liens arête");
        jMenuItemLiensArete.setToolTipText("");
        jMenuItemLiensArete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLiensAreteActionPerformed(evt);
            }
        });
        jMenuFiltres.add(jMenuItemLiensArete);

        jMenuItemVoisinsDirects.setText("Voisins directs");
        jMenuItemVoisinsDirects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVoisinsDirectsActionPerformed(evt);
            }
        });
        jMenuFiltres.add(jMenuItemVoisinsDirects);

        jMenuItemCheminCourt.setText("Chemin le plus court");
        jMenuItemCheminCourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheminCourtActionPerformed(evt);
            }
        });
        jMenuFiltres.add(jMenuItemCheminCourt);

        jMenuItemFiabilité.setText("Fiabilité");
        jMenuItemFiabilité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiabilitéActionPerformed(evt);
            }
        });
        jMenuFiltres.add(jMenuItemFiabilité);

        jMenuItemCriteres.setText("Critères");
        jMenuFiltres.add(jMenuItemCriteres);

        jMenuBarOptions.add(jMenuFiltres);

        setJMenuBar(jMenuBarOptions);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItemListeSommetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListeSommetsActionPerformed
        // TODO add your handling code here:
        jDialogListe.setSize(400,300);
        jDialogListe.setVisible(true);
        jDialogListe.setLocationRelativeTo(null);
        jTextAreaListe.setText(g.getListeSommets().toString());
    }//GEN-LAST:event_jMenuItemListeSommetsActionPerformed

    private void jMenuItemOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirActionPerformed
        // TODO add your handling code here:
        Chargement.ouverture();
    }//GEN-LAST:event_jMenuItemOuvrirActionPerformed

    private void jMenuItemListeAretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListeAretesActionPerformed
        // TODO add your handling code here:
        jDialogAretes.setSize(400,300);
        jDialogAretes.setVisible(true);
        jDialogAretes.setLocationRelativeTo(null);
        jTextAreaListe.setText(g.getListeAretes().toString());
    }//GEN-LAST:event_jMenuItemListeAretesActionPerformed

    private void jMenuItemLiensSommetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLiensSommetActionPerformed
        // TODO add your handling code here:
        jDialogLiens.setSize(400,300);
        jDialogLiens.setVisible(true);
        jDialogLiens.setLocationRelativeTo(null);
        //jTextAreaListe.setText(g..toString());
    }//GEN-LAST:event_jMenuItemLiensSommetActionPerformed

    private void jMenuItemLiensAreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLiensAreteActionPerformed
        // TODO add your handling code here:
        jDialogLiensA.setSize(400,300);
        jDialogLiensA.setVisible(true);
        jDialogLiensA.setLocationRelativeTo(null);
        //jTextAreaListe.setText(g..toString());
    }//GEN-LAST:event_jMenuItemLiensAreteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItemVoisinsDirectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoisinsDirectsActionPerformed
        // TODO add your handling code here:
        jDialogVoisinsD.setSize(400,300);
        jDialogVoisinsD.setVisible(true);
        jDialogVoisinsD.setLocationRelativeTo(null);
        //jTextAreaListe.setText(g..toString());
    }//GEN-LAST:event_jMenuItemVoisinsDirectsActionPerformed


    private void jMenuItemModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifierActionPerformed
        // TODO add your handling code here:
        JFileChooser dossier = new JFileChooser();
            
            dossier.setCurrentDirectory(new File("." + File.separator));
            FileNameExtensionFilter typeFichier = new FileNameExtensionFilter("Fichiers de type csv","csv");
            dossier.setFileFilter(typeFichier);
            
            int reponse = dossier.showDialog(dossier, "Ouvrir");
            
            if(reponse == JFileChooser.APPROVE_OPTION) {
                File selectedFile = dossier.getSelectedFile();
                String filePath = selectedFile.getAbsolutePath();
            
                // Vérifier si le système de bureau est pris en charge pour ouvrir des fichiers
                if (Desktop.isDesktopSupported()) {
                    Desktop bureau = Desktop.getDesktop();
                    try {
                        bureau.open(selectedFile);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
            }
            }
    }//GEN-LAST:event_jMenuItemModifierActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItemCheminCourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheminCourtActionPerformed
        // TODO add your handling code here:
        jDialogCheminCourt.setSize(600,350);
        jDialogCheminCourt.setLocationRelativeTo(null);
        jDialogCheminCourt.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheminCourtActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItemFiabilitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiabilitéActionPerformed
        // TODO add your handling code here:
        jDialogFiabilite.setSize(600,350);
        jDialogFiabilite.setLocationRelativeTo(null);
        jDialogFiabilite.setVisible(true);
    }//GEN-LAST:event_jMenuItemFiabilitéActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jDialog;
    private javax.swing.JDialog jDialogAretes;
    private javax.swing.JDialog jDialogCheminCourt;
    private javax.swing.JDialog jDialogFiabilite;
    private javax.swing.JDialog jDialogLiens;
    private javax.swing.JDialog jDialogLiensA;
    private javax.swing.JDialog jDialogListe;
    private javax.swing.JDialog jDialogVoisinsD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JMenuBar jMenuBarOptions;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenu jMenuFiltres;
    private javax.swing.JMenuItem jMenuItemCheminCourt;
    private javax.swing.JMenuItem jMenuItemCriteres;
    private javax.swing.JMenuItem jMenuItemFiabilité;
    private javax.swing.JMenuItem jMenuItemLiensArete;
    private javax.swing.JMenuItem jMenuItemLiensSommet;
    private javax.swing.JMenuItem jMenuItemListeAretes;
    private javax.swing.JMenuItem jMenuItemListeSommets;
    private javax.swing.JMenuItem jMenuItemModifier;
    private javax.swing.JMenuItem jMenuItemOuvrir;
    private javax.swing.JMenuItem jMenuItemVoisinsDirects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaListe;
    private javax.swing.JTextArea jTextAreaListe1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
