/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import graphe.*;
import static graphe.Chargement.g;

/**
 *
 * @author rafik
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogListe = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaListe = new javax.swing.JTextArea();
        jDialogArretes = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaListe1 = new javax.swing.JTextArea();
        jDialogLiens = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBarOptions = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemOuvrir = new javax.swing.JMenuItem();
        jMenuItemModifier = new javax.swing.JMenuItem();
        jDialog = new javax.swing.JMenu();
        jMenuItemVoisinsDirects = new javax.swing.JMenuItem();
        jMenuItemLiensArete = new javax.swing.JMenuItem();
        jMenuItemListeSommets = new javax.swing.JMenuItem();
        jMenuItemListeAretes = new javax.swing.JMenuItem();
        jMenuFiltres = new javax.swing.JMenu();
        jMenuItemCriteres = new javax.swing.JMenuItem();
        jMenuItemFiabilité = new javax.swing.JMenuItem();
        jMenuItemCheminCourt = new javax.swing.JMenuItem();

        jTextAreaListe.setColumns(20);
        jTextAreaListe.setLineWrap(true);
        jTextAreaListe.setRows(5);
        jScrollPane6.setViewportView(jTextAreaListe);

        javax.swing.GroupLayout jDialogListeLayout = new javax.swing.GroupLayout(jDialogListe.getContentPane());
        jDialogListe.getContentPane().setLayout(jDialogListeLayout);
        jDialogListeLayout.setHorizontalGroup(
            jDialogListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jDialogListeLayout.setVerticalGroup(
            jDialogListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListeLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTextAreaListe1.setColumns(20);
        jTextAreaListe1.setLineWrap(true);
        jTextAreaListe1.setRows(5);
        jScrollPane7.setViewportView(jTextAreaListe1);

        javax.swing.GroupLayout jDialogArretesLayout = new javax.swing.GroupLayout(jDialogArretes.getContentPane());
        jDialogArretes.getContentPane().setLayout(jDialogArretesLayout);
        jDialogArretesLayout.setHorizontalGroup(
            jDialogArretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogArretesLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jDialogArretesLayout.setVerticalGroup(
            jDialogArretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogArretesLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel5.setText("Sommet à traiter");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        javax.swing.GroupLayout jDialogLiensLayout = new javax.swing.GroupLayout(jDialogLiens.getContentPane());
        jDialogLiens.getContentPane().setLayout(jDialogLiensLayout);
        jDialogLiensLayout.setHorizontalGroup(
            jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensLayout.createSequentialGroup()
                .addGroup(jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogLiensLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5))
                    .addGroup(jDialogLiensLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jDialogLiensLayout.setVerticalGroup(
            jDialogLiensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogLiensLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface d'aide à la décision");
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Ajouter");
        jButton1.setEnabled(false);

        jButton2.setText("Supprimer");
        jButton2.setEnabled(false);

        jTextPane1.setEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setText("Temps moyen");

        jTextPane2.setEnabled(false);
        jScrollPane2.setViewportView(jTextPane2);

        jLabel2.setText("Distance");

        jTextPane3.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane3);

        jLabel3.setText("Fiabilité");

        jTextPane4.setEnabled(false);
        jScrollPane4.setViewportView(jTextPane4);

        jLabel4.setText("Type de dispensaire");

        jButton3.setText("Modifier");
        jButton3.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuFichier.setText("Fichier");

        jMenuItemOuvrir.setText("Ouvrir");
        jMenuItemOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemOuvrir);

        jMenuItemModifier.setText("Modifier");
        jMenuFichier.add(jMenuItemModifier);

        jMenuBarOptions.add(jMenuFichier);

        jDialog.setText("Affichage");

        jMenuItemVoisinsDirects.setText("Voisins directs");
        jDialog.add(jMenuItemVoisinsDirects);

        jMenuItemLiensArete.setText("Liens arête");
        jDialog.add(jMenuItemLiensArete);

        jMenuItemListeSommets.setText("Liste sommets");
        jMenuItemListeSommets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListeSommetsActionPerformed(evt);
            }
        });
        jDialog.add(jMenuItemListeSommets);

        jMenuItemListeAretes.setText("Liste arêtes");
        jMenuItemListeAretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListeAretesActionPerformed(evt);
            }
        });
        jDialog.add(jMenuItemListeAretes);

        jMenuBarOptions.add(jDialog);

        jMenuFiltres.setText("Filtres");

        jMenuItemCriteres.setText("Critères");
        jMenuFiltres.add(jMenuItemCriteres);

        jMenuItemFiabilité.setText("Fiabilité");
        jMenuFiltres.add(jMenuItemFiabilité);

        jMenuItemCheminCourt.setText("Chemin le plus court");
        jMenuFiltres.add(jMenuItemCheminCourt);

        jMenuBarOptions.add(jMenuFiltres);

        setJMenuBar(jMenuBarOptions);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItemListeSommetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListeSommetsActionPerformed
        // TODO add your handling code here:
        jDialogListe.setSize(400,300);
        jDialogListe.setVisible(true);
        jDialogListe.setLocationRelativeTo(null);
        jTextAreaListe.setText(g.getListeSommets().toString());
    }//GEN-LAST:event_jMenuItemListeSommetsActionPerformed

    private void jMenuItemOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirActionPerformed
        // TODO add your handling code here:
        Chargement.ouverture();
    }//GEN-LAST:event_jMenuItemOuvrirActionPerformed

    private void jMenuItemListeAretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListeAretesActionPerformed
        // TODO add your handling code here:
        jDialogListe.setSize(400,300);
        jDialogListe.setVisible(true);
        jDialogListe.setLocationRelativeTo(null);
        jTextAreaListe.setText(g.getListeAretes().toString());
    }//GEN-LAST:event_jMenuItemListeAretesActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jDialog;
    private javax.swing.JDialog jDialogArretes;
    private javax.swing.JDialog jDialogLiens;
    private javax.swing.JDialog jDialogListe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBarOptions;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenu jMenuFiltres;
    private javax.swing.JMenuItem jMenuItemCheminCourt;
    private javax.swing.JMenuItem jMenuItemCriteres;
    private javax.swing.JMenuItem jMenuItemFiabilité;
    private javax.swing.JMenuItem jMenuItemLiensArete;
    private javax.swing.JMenuItem jMenuItemListeAretes;
    private javax.swing.JMenuItem jMenuItemListeSommets;
    private javax.swing.JMenuItem jMenuItemModifier;
    private javax.swing.JMenuItem jMenuItemOuvrir;
    private javax.swing.JMenuItem jMenuItemVoisinsDirects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextAreaListe;
    private javax.swing.JTextArea jTextAreaListe1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
